- .readthedocs.yaml
This PR adds a [Read the Docs configuration file](https://docs.readthedocs.io/en/stable/config-file/index.html).
The proposed config file is an amalgam of:
- [a Read the Docs example from the documentation](https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-poetry)
- [pdm's .readthedocs.yaml](https://github.com/pdm-project/pdm/blob/main/.readthedocs.yaml)
In order to test it out, I already leaned forward and created a SARkit project in Read the Docs and currently have it configured to a this branch:
See the docs here: https://sarkit.readthedocs.io/en/latest/
> add Read the Docs config file

- sarkit/standards/cphd/io.py
- sarkit/standards/sicd/__init__.py
- sarkit/standards/sicd/io.py
- sarkit/standards/sidd/io.py
- tests/standards/sicd/test_io.py
This PR standardizes the io interfaces around file objects, which was first proposed when SIDD I/O was introduced as a way to simplify the code/API as a lesson learned from some SARPy issues:
- https://github.com/ngageoint/sarpy/pull/524
- https://github.com/ngageoint/sarpy/pull/526
This change impacted `sarkit.standards.sicd.read_sicd_xml`. I was going to update the function but it seems like an outlier (CPHD/SIDD do not have them) that went against the spirit of these standardized interfaces so I propose removing it.
- add some missing type hints
- add types to properties in class docstrings to make them render similarly to non-properties
> Standardize I/O interfaces around file objects

- sarkit/verification/sicd_consistency.py
- tests/verification/test_sicd_consistency.py
While testing with `RGAZCOMP` xml, I discovered that the IFA test was failing.  This is due to a mismatch in the `ImageFormation/ImageFormAlgo` and the node name from the spec and schema, which is CamelCase.  `RGAZCOMP` vs `RgAzComp`.
Here's a simple fix...
<details>
<summary>Failed testing from main</summary>
```
$ pdm run nox
nox > Running session lint
nox > Creating virtual environment (virtualenv) using python in .nox/lint
nox > pdm install --frozen-lockfile -G dev-lint
INFO: Inside an active virtualenv /home/vscuser/repos/ext_sarkit/.nox/lint, reusing it.
Set env var PDM_IGNORE_ACTIVE_VENV to ignore it.
Synchronizing working set with resolved packages: 45 to add, 0 to update, 0 to remove
✔ Install alabaster 1.0.0 successful
✔ Install colorlog 6.9.0 successful
✔ Install argcomplete …
```
> Bugfix - node name mismatch

- README.md
- sarkit/processing/pixel_type.py
- sarkit/standards/sicd/io.py
- tests/standards/sicd/test_io.py
This PR applies the I/O conventions of the CPHD reader/writer to SICD:
- `read_image` returns an array whose dtype is appropriate for the PixelType
- `write_image` requires an array whose dtype is appropriate for the PixelType; will byteswap if necessary
In addition, since #8 has been merged and the asset is available in github on main, the image src in the README has been swapped out.
After running the new unittest (`pytest tests/standards/sicd/test_io.py::test_roundtrip`):
```python
import pathlib
import sarkit.standards.sicd as ss
for sicd in pathlib.Path("/data/tmp/pytest-of-vscuser/pytest-current/").rglob("out.sicd"):
with open(sicd, "rb") as f, ss.SicdNitfReader(f) as r:
print(sicd.parent)
print(r.sicd_xmltree.findtext(".//{*}PixelType"))
print(r.read_image().dtype)
print()
``` …
> SICD IO: support other pixel types

- sarkit/standards/cphd/io.py
- sarkit/standards/sicd/projection/calc.py
- sarkit/standards/sicd/xml.py
- tests/standards/cphd/test_io.py
As a follow-on to #12, this PR updates `CphdWriter.write_support_array` to:
- accommodate writing masked arrays
- add dtype/shape/value checks (ala `SicdNitfWriter.write_signal`)
- raises `ValueError` if masked array's fill value does not match the XML AND the array uses the fill value
- changed from `ndarray.tofile` to `_file_object.write`
- masked arrays don't implement `tofile` yet and in an effort to create a more flexible API, we want to move to `seek`, `write`, and `read` anyways
- minor cleanup
> CPHD IO: Support writing masked support arrays

- sarkit/standards/sicd/projection/__init__.py
- sarkit/standards/sicd/projection/calc.py
- sarkit/standards/sicd/projection/derived.py
- sarkit/standards/sicd/projection/params.py
- tests/standards/sicd/test_projection.py
Implement the equations from section `8 Adjustable Parameters` from NGA.STND.0024-3_1.4.0_SICD_IPDD_2024_05_01
The names were chosen to closely match the document for traceability.  Included a smoke test for monostatic and bistatic cases.
<details>
<summary>Tests pass</summary>
```
$ pdm run nox
nox > Running session lint
nox > Creating virtual environment (virtualenv) using python in .nox/lint
nox > pdm sync --prod -G dev-lint
INFO: Inside an active virtualenv /home/vscuser/repos/sarkit/.nox/lint, reusing it.
Set env var PDM_IGNORE_ACTIVE_VENV to ignore it.
Synchronizing working set with resolved packages: 6 to add, 0 to update, 0 to remove
✔ Install mypy-extensions 1.0.0 successful
✔ Install typing-extensions 4.12.2 successful
✔ Install lxml 5.3.0 successful
✔ Install mypy 1.14.1 …
```
> Add apo adjustments to projections

- sarkit/standards/sicd/projection/calc.py
- tests/standards/sicd/test_projection.py
This is meant to address the issues @mstewart-vsc found while trying to use the projection code.  I  duplicated the problem by simply changing the test code to project multiple points.  Here's a snip from error that is produced.
I used `np.newaxis` to orient the various components to produce the correct output and improved the unit tests to use multi-dimensional input.
<details>
<summary>New Tests Pass</summary>
```
$ pdm run nox
nox > Running session lint
nox > Creating virtual environment (virtualenv) using python in .nox/lint
nox > pdm sync --prod -G dev-lint
INFO: Inside an active virtualenv /home/vscuser/repos/ext_sarkit/.nox/lint, reusing it.
Set env var PDM_IGNORE_ACTIVE_VENV to ignore it.
Synchronizing working set with resolved packages: 6 to add, 0 to update, 0 to remove
✔ …
```
> Bugfix: Projecting Multiple Grid Locations

- sarkit/verification/consistency.py
- sarkit/verification/cphd_consistency.py
- sarkit/verification/crsd_consistency.py
- sarkit/verification/sicd_consistency.py
- tests/verification/test_consistency.py
- tests/verification/test_crsd_consistency.py
While saving the output of a consistency checker to a text file, I wanted to disable the color output. This PR adds the ability to control this to the consistency checkers explicitly and via [NO_COLOR](https://no-color.org/):
- moves common CLI stuff into `consistency.py`
- remove `check_signal_data` from `crsd_consistency` as it is currently unused
> verification: move common CLI args/calls to base class; add NO_COLOR args

- docs/source/conf.py
- docs/source/user_guide.rst
- sarkit/cphd/__init__.py
- sarkit/cphd/_io.py
- sarkit/crsd/__init__.py
- sarkit/crsd/_io.py
- sarkit/sicd/__init__.py
- sarkit/sicd/_io.py
- sarkit/sidd/__init__.py
- sarkit/sidd/_io.py
- sarkit/verification/_cphd_consistency.py
- sarkit/verification/_crsd_consistency.py
- tests/core/cphd/test_io.py
- tests/core/crsd/test_io.py
- tests/core/sicd/test_io.py
- tests/core/sidd/test_io.py
- tests/verification/test_cphd_consistency.py
- tests/verification/test_crsd_consistency.py
- tests/verification/test_sicd_consistency.py
As mentioned in #22, this PR aims to improve the IO API, primarily by proposing more descriptive, less-redundant names but also by tweaking the concept of "Plans" into a settable "Metadata" classes that are perhaps more natural to move across readers and writers, and also by improving the API documentation by way of more rigorous examples.
Docs for this PR can be found here: https://sarkit.readthedocs.io/en/io-api-iteration/
- removes redundant `Fmt` from `sarkit.fmt.FmtObj` -> `sarkit.fmt.Obj` and from some scoped kwargs (e.g. `CphdPlan(cphd_xmltree=...)` --> `Metadata(xmltree=...)`
- use suffix `Part` on objects that only surface certain fields of the things they represent
- `sarkit.cphd.CphdFileHeaderFields` -> `sarkit.cphd.FileHeaderPart`
- `Plan`s are now `Metadata`
- this was …
> Improve IO API

- docs/source/conf.py
- noxfile.py
- sarkit/_xmlhelp.py
- sarkit/cphd/_io.py
- sarkit/sicd/_io.py
- sarkit/sicd/projection/_params.py
- sarkit/verification/_sicd_consistency.py
Semi-regularly, I've inadvertently broken links/references in the documentation while working on changes. I think it would be useful to enable [`--nitpicky` in sphinx-build](https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-n) so that we can hopefully identify/address these as they crop up without having to just find them in the rendered docs later. Here was the log before I made the changes:
```
/home/vscuser/git/glweb/software/third-party/sarkit/sarkit/_xmlhelp.py:docstring of sarkit._xmlhelp.XyzPolyType.parse_elem:14: WARNING: py:obj reference target not found: N [ref.obj]
/home/vscuser/git/glweb/software/third-party/sarkit/sarkit/_xmlhelp.py:docstring of sarkit._xmlhelp.XyzPolyType.set_elem:10: WARNING: py:obj reference target not found: N [ref.obj] …
```
> Docs: identify/fix missing references

- sarkit/sicd/projection/__init__.py
- sarkit/sicd/projection/_calc.py
- sarkit/sicd/projection/_derived.py
- sarkit/sicd/projection/_params.py
- tests/core/sicd/test_projection.py
The dimensionality and behavior of SARkit's SICD projection dataclasses' attributes is undocumented and perhaps adopts an unintuitive behavior borne from convenience in the arithmetic inside some functions themselves. This PR proposes the following changes to address these deficiencies:
- split `CoaPosVels` and `ProjectionSets` into monostatic and bistatic variants
- use TypeAliases to maintain/document interfaces that accept/produce both
- better document constructor behavior and attribute dimensionality in said classes
- add broadcasting/asarray to constructors to make these more convenient for users to instantiate
- make some interfaces more explicit
- remove unused args from `r_rdot_from_<>` functions
- change `compute_pt_r_rdot_parameters` to use explicit Xmt/Rcv position velocities
> Document dimensionality/broadcast behavior of SICD projection dataclasses

- sarkit/cphd/_io.py
- sarkit/verification/__init__.py
- sarkit/verification/_consistency.py
- sarkit/verification/_cphd_consistency.py
- sarkit/verification/_crsd_consistency.py
- sarkit/verification/_sicd_consistency.py
- tests/verification/test_cphd_consistency.py
- tests/verification/test_crsd_consistency.py
- tests/verification/test_sicd_consistency.py
The current consistency API is largely a holdover from SARPy and early VSC tools and as such is a bit out of touch with the rest of SARkit. This PR proposes a few changes to the consistency API to simplify, clarify, and match the rest of SARkit.
- CLI
- remove `--version` (only used in `check_file_type_header`; get from file instead)
- change `--signal-data` to `--thorough`; the current help is a lie, so I wanted to come up with a name and description that better described what is actually going on
- CphdConsistency
- change constructor to:
- remove `version_override` (see above)
- accept `file_type_header` str (replaces version; natural complement to kvp_list, see `skcrsd.read_file_header` and new `from_parts` method
- rename `cphdroot` to `cphd_xml` (because it doesn't have to be the …
> Consistency API revision

- sarkit/sicd/__init__.py
- sarkit/sicd/projection/__init__.py
- sarkit/sicd/projection/_calc.py
- sarkit/sicd/projection/_derived.py
- tests/core/sicd/test_projection.py
- tests/core/sicd/test_sicd_projections.py
This PR adds functionality for SICD IPDD Section 10 (Precise R/Rdot to DEM Surface Projection) to `sarkit.sicd`:
- `sarkit.sicd.image_to_dem_surface`
- `sarkit.sicd.projection.r_rdot_to_dem_surface`
- SICD v1.4 (and earlier) only support monostatic DEM projection
- tried to adapt a [numpydoc guideline](https://numpydoc.readthedocs.io/en/latest/format.html#method-docstrings) to reduce docstring copy-paste between the methods in `sarkit.sicd.projection` and the derived methods in `sarkit.sicd`
> SICD: Precise R/Rdot to DEM Surface Projection (monostatic)

- pyproject.toml
This PR broadens numpy support to include `>=1.25.0` to match https://scientific-python.org/specs/spec-0000/
> Support numpy>=1.25.0

- noxfile.py
This PR fixes a latent bug wherein our `lint` nox session is calling mypy in a session that does not explicitly install all dependencies. Although it isn't causing any issues for now, if an extra were to add a dependency with typing, mypy would fail to find it.
> Bugfix: make sure all deps are installed before type checking

- sarkit/verification/_sicd_consistency.py
- tests/verification/test_cphd_consistency.py
- tests/verification/test_crsd_consistency.py
- tests/verification/test_sicd_consistency.py
- tests/verification/testing.py
This PR fixes a bug found when running `sicd-consistency` against a SICD NITF with more than one image segment. For the multiple-image-segment case, there is a mismatch in the "actual" values (which were being stripped of whitespace) and the "expected" values which were being padded with whitespace.
The new test fails when run in `main`:
<details><summary>new test in main</summary>
```
pdm run pytest tests/verification/test_sicd_consistency.py::test_check_nitf_imseg
======================================================================================================================================================================= test session starts ============================================================================================================================================= …
```
> Bugfix: SicdConsistency.check_nitf_imseg IID1s

- .github/workflows/tests.yml
- .gitlab-ci.yml
- .readthedocs.yaml
- README.md
- pyproject.toml
This PR adds explicit python=3.13 support to SARkit in accordance with [Scientific Python SPEC0](https://scientific-python.org/specs/spec-0000/).
- update classifier in pyproject.toml
- add [SPEC0 badge](https://scientific-python.org/specs/spec-0000/#badges) to README to communicate/capture our dependency strategy
- test with python=3.13 in gitlab/github CI
- use [python=3.13 in RTD](https://docs.readthedocs.com/platform/stable/config-file/v2.html#build-tools-python)
I activated a hidden RTD build from this branch to demonstrate that RTD works as expected: https://sarkit.readthedocs.io/en/python-3.13-support/
> python 3.13 support

- sarkit/cphd/_io.py
- tests/core/cphd/test_io.py
Credit to @bombaci-vsc for finding this. When attempting to create a CPHD Writer for an XML without support arrays, the logic for determining the support block size is run unnecessarily and errors out:
<details><summary>snippet of new test failure when run before the fix</summary>
```
>       support_block_size = max(
sa["size"] + sa["offset"] for sa in self._sa_size_offsets.values()
)
E       ValueError: max() iterable argument is empty
sarkit/cphd/_io.py:673: ValueError
================================================================================================================================================================ short test summary info ========================================================================================================================================== …
```
> Bugfix: write CPHDs without support arrays

- README.md
- data/example-crsd-1.0.xml
- data/syntax_only/crsd/0000-syntax-only-crsd-1.0.xml
- data/syntax_only/crsd/0001-syntax-only-crsd-1.0.xml
- data/syntax_only/crsd/0002-syntax-only-crsd-1.0.xml
- data/syntax_only/crsd/0003-syntax-only-crsd-1.0.xml
- data/syntax_only/crsd/make_syntax_only_crsd_xmls.py
- data/syntax_only/crsd/manual-syntax-only-crsd-mono-sar-1.0.xml
- docs/source/user_guide.rst
- sarkit/crsd/__init__.py
- sarkit/crsd/_io.py
- sarkit/crsd/schemas/NGA.STND.0080-2_1.0_CRSD_schema_2025_02_25.xsd
- sarkit/verification/_crsd_consistency.py
- tests/core/crsd/test_io.py
- tests/verification/test_crsd_consistency.py
CRSD v1.0 is now posted on the nsgreg:
- https://nsgreg.nga.mil/doc/view?i=5672
- https://nsgreg.nga.mil/doc/view?i=5673
This PR:
- replaces the schema with the one from nsgreg
- updates namespaces/file names as appropriate
- removes draft markings
- updates docs with links/citations
> Remove CRSD draft markings, use schema posted on nsgreg

- sarkit/sidd/_io.py
This PR addresses the `np.sum(generator)` [DeprecationWarning](https://github.com/ValkyrieSystems/sarkit/actions/runs/16004280135/job/45146935947#step:5:60) in `sarkit.sidd._io`:
```
tests/core/sidd/test_io.py: 24 warnings
/home/runner/work/sarkit/sarkit/sarkit/sidd/_io.py:891: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
shape[0] = np.sum(imseg["subheader"]["NROWS"].value for imseg in imsegs)
```
> address np.sum(generator) deprecation warning

- pyproject.toml
- sarkit/_iohelp.py
- sarkit/cphd/_io.py
- sarkit/crsd/_io.py
- sarkit/sicd/_io.py
- sarkit/sidd/_io.py
- tests/core/cphd/test_io.py
- tests/core/crsd/test_io.py
- tests/core/sicd/test_io.py
- tests/core/sidd/test_io.py
- tests/core/test_iohelp.py
This branch attempts to address the issue raised in https://github.com/ValkyrieSystems/sarkit/issues/45
The primary impediment was `np.fromfile` and this branch removes it from the repo, replacing it with a stripped-down version that does not create a memmap.
Tests have been added to verify that web-hosted synthetic data can be read.
Closes #45
> Support remote file reading

- sarkit/verification/_cphd_consistency.py
This modifies the various `Fixed` CPHD node checks to not have a tolerance.  This matches the approach used in CRSD.
Previously if the min and max values were very close (but different) and fixed was `false`, cphd-consistency would emit a warning that the values weren't different enough.
> Remove approx from cphd fixed value checks

- docs/source/user_guide.rst
- pyproject.toml
- sarkit/verification/_cphd_consistency.py
- sarkit/verification/_crsd_consistency.py
- sarkit/verification/_sicd_consistency.py
- sarkit/verification/_sidd_consistency.py
- tests/verification/test_cphd_consistency.py
- tests/verification/test_crsd_consistency.py
- tests/verification/test_sicd_consistency.py
- tests/verification/test_sidd_consistency.py
This modifies the consistency checker CLIs to use `smart_open.open` if it is available.  
```
$ cphd-consistency http://umbra-open-data-catalog.s3.amazonaws.com/sar-data/tasks/3e56976b-fa2b-4035-bb71-385efde84c4a/2025-06-22-23-57-52_UMBRA-10/2025-06-22-23-57-52_UMBRA-10_CPHD.cphd
check_channel_fx_osr_Primary: FX domain vectors are sufficiently sampled for channel Primary.
[Error] Need: FX_OSR is at least 1.1
[Warning] Want: FX_OSR is at least 1.2
```
> Use smart_open in CLI utililties

- data/syntax_only/sidd/0000-syntax-only-sidd-3.0.xml
- data/syntax_only/sidd/0001-syntax-only-sidd-3.0.xml
- data/syntax_only/sidd/0002-syntax-only-sidd-3.0.xml
- sarkit/sicd/_xml.py
- sarkit/sidd/_xml.py
- sarkit/xmlhelp/_transcoders.py
- tests/core/xmlhelp/test_transcoders.py
This PR addresses a bug where SARkit is coercing all XDT metadata items to UTC; even in the rare circumstances where this is not correct, e.g. SIDD 3.0.0's `ExploitationFeatures/Collection/Information/LocalDateTime`:
This can be illustrated by running the following script:
<details><summary>tmp.py</summary>
<p>
```python
import datetime
import lxml.etree
import sarkit.sidd as sksidd
wrapped_sidd = sksidd.ElementWrapper(lxml.etree.Element("{urn:SIDD:3.0.0}SIDD"))
dt_local = datetime.datetime.now()
dt_utc = dt_local.astimezone(tz=datetime.UTC)
print(f"{dt_utc=}\n{dt_local=}\n\n")
wrapped_sidd["ExploitationFeatures"].add("Collection")["Information"] = {
"CollectionDateTime": dt_utc,
"LocalDateTime": dt_local,
}
lxml.etree.dump(wrapped_sidd.elem.find(".//{*}Information"))
```
</p>
</details> …
> Bugfix: non-UTC XDT handling

- docs/source/user_guide.rst
- pyproject.toml
- sarkit/cphd/__init__.py
- sarkit/crsd/__init__.py
- sarkit/sicd/__init__.py
- sarkit/sidd/__init__.py
- sarkit/verification/__init__.py
- sarkit/verification/_cphd_consistency.py
- sarkit/verification/_cphdcheck.py
- sarkit/verification/_crsd_consistency.py
- sarkit/verification/_crsdcheck.py
- sarkit/verification/_sicd_consistency.py
- sarkit/verification/_sicdcheck.py
- sarkit/verification/_sidd_consistency.py
- sarkit/verification/_siddcheck.py
- tests/verification/test_cli.py
- tests/verification/test_cphd_consistency.py
- tests/verification/test_crsd_consistency.py
- tests/verification/test_sicd_consistency.py
- tests/verification/test_sidd_consistency.py
This renames the command line consistency checkers from `<format>-consistency` to `<format>check`.  This removes the hyphen and provides a shorter name to go along with the `<format>info` utilities.
> Renamed consistency checker CLIs

- CHANGELOG.md
- sarkit/sicd/projection/__init__.py
- sarkit/sicd/projection/_calc.py
- sarkit/sicd/projection/_derived.py
- sarkit/sicd/projection/_errorprop.py
- tests/core/sicd/test_errorprop.py
- tests/core/sicd/test_projection.py
This PR aims to smooth out some of the API differences between `main` and `integration/sicd-1.5`, such that merging `integration/sicd-1.5` into `main` in the future will not cause any compatibility-breaking changes.
- renaming `compute_and_apply_offsets` -> `apply_apos`
- refactor `compute_ecef_pv_covariance` -> `compute_ecef_pv_transformation`
- hide _sensitivity methods from public API (for now)
> SICD sensitivity API tweaks in preparation for SICD v1.5

- CHANGELOG.md
- generate_xsdtypes.py
- sarkit/sicd/_constants.py
- sarkit/sicd/_xml.py
- sarkit/sicd/schemas/SICD_schema_V1.4.0_2024_05_01.xsd
- sarkit/sicd/xsdtypes/SICD_schema_V1.4.0_2024_05_01.json
This PR replaces the deprecated SICD v1.4.0 schema (dated 2023-10-26) with the most recent version that superseded it on 2024-05-01.
See this entry from the SICD v1.4.0 vol 1 revision history:
- fix header levels in CHANGELOG.md
- remove unused `output_dir` arg from `generate_xsdtypes.py`
> Bugfix: replace SICD v1.4.0 schema with 2024-05-01 version 

- CHANGELOG.md
- sarkit/_iohelp.py
- tests/utils.py
This changes `_iohelper.fromfile` to use `readinto()`.  This eliminates the need for the extra buffer and generally has lower overhead.
> optimize fromfile using readinto
